### ISSUE TITLE
Serial console not implemented

### ISSUE THREAD

**Issue by SchneHa** [ElektorLabs/150500-DIY-Soldering-Station#1]
The Elektor article describes that the setpoint and actual value of the temperature and the status of the soldering station is shown in serial console via USB-serial. That isn't implemented in firmware. Is it planned to release an update?

**Comment by lab-mathias-claussen** [comment]
Hello,
indedd the serial commandline interface is missing from the current build. And yes, it is intendet to add this features to the firmware. 

Best Regards

**Comment by lab-mathias-claussen** [comment]
The interface is implemented ( see current version in git ) 
For now i close this issue, if there are problems with the interface please open a new issue 
Best Regards
